# Generated by Django 5.2 on 2025-04-09 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('improve_endurance', 'Improve Endurance'), ('general_health', 'General Health')], max_length=50)),
                ('description', models.TextField()),
                ('target_metric', models.CharField(help_text="E.g. 'Lose 10 lbs' or 'Run 5K under 25 mins'", max_length=100)),
                ('target_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
