# Generated by Django 5.1.8 on 2025-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='target_metric',
            field=models.CharField(max_length=100),
        ),
    ]
