# Generated by Django 5.1.5 on 2025-04-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_savedexercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedexercise',
            old_name='name',
            new_name='exercise_name',
        ),
    ]
