# Generated by Django 5.1.5 on 2025-04-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_rename_name_savedexercise_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedexercise',
            name='secondaryMuscles',
            field=models.TextField(blank=True, default=''),
        ),
    ]
