# Generated by Django 5.1.8 on 2025-04-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_challenge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
