# Generated by Django 5.1.8 on 2025-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_delete_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('challenge_type', models.CharField(choices=[('weight_lifted', 'Weight Lifted'), ('active_days', 'Active Days')], max_length=20)),
                ('members', models.JSONField(default=dict)),
            ],
        ),
    ]
